### ISSUE TITLE
How to enable code editor with syntax higlighting for php files?

### ISSUE THREAD

**Issue by olpo24** [Offerel/roundcube_storage#8]
Hi,

hi to enable a code editor with syntax highlighting for php files?

By default your config allows only to edit php files with simple texteditor or onlineconvert.

Best regards,

Ole

**Comment by Offerel** [comment]
There are currently no configuration parameters to open special file types with a dedicated editor. Maybe this possible directly via elFinder (https://github.com/Studio-42/elFinder). Since a special PHP editor is not the main focus of this plugin, it is not planned to implement such a function. So the risk is very high that your own adjustments to the elFinder files will be overwritten with an update of the plugin.
