### ISSUE TITLE
Common folder

### ISSUE THREAD

**Issue by VBlack2019** [Offerel/roundcube_storage#9]
good day
Thank you for your plugin.
Is it possible to add a connection common to all the local folder or home drive (cifs)?

**Comment by Offerel** [comment]
Sure. You can use all directory, which are mounted in to your file system.

**Comment by VBlack2019** [comment]
This is an additional, common to all folder. Without %u

**Comment by Offerel** [comment]
Hmm i didn't understand what you mean. Using %u is a optional shortcut. Its replaced with the roundcube username. It is not mandatory, only optional. If you skip it, you can use any local folder path.

If you mean a additional root folder, additional to the users folder, it's possible to use symlinks in the userfolder. With that, you didn't have a additional root folder, but you can access other folders to. Using bind-mount is also possible.

I know, with elFinder you can have multiple roots. But since the purpose of the plugin is to give a Roundcube user a personal folder for his files, this is not directly supported by my implementation. But you are welcome to fork the plugin and customize it to your needs.
